spring:
  datasource:
    url: jdbc:h2:mem:testdb
  sql:
    init:
      mode: always


  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: false

logging:
  level:
    ROOT: ERROR
    ru:
      otus:
        jpaevents:
          listeners: INFO
